import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Exo_2, Righteous } from "next/font/google"; // ✅ Added
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// ✅ Added Exo 2
const exo2 = Exo_2({
  variable: "--font-exo2",
  subsets: ["latin"],
});

// ✅ Added Righteous
const righteous = Righteous({
  variable: "--font-righteous",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AYURVEDA App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${exo2.variable} ${righteous.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
